import { Express } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import faqRoutes from '../modules/faq/faq.routes.js';
import communityRoutes from '../modules/community/community.routes.js';
import searchRoutes from '../modules/search/search.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import adminAuditRoutes from '../modules/admin/admin-audit.routes.js';
import adminAutoAnswerRoutes from '../modules/admin/admin-auto-answer.routes.js';
import analyticsRoutes from '../modules/search/analytics.routes.js';
import notificationRoutes from '../modules/notification/notification.routes.js';
import teaRoutes from '../modules/notification/tea.routes.js';
import reputationRoutes from '../modules/moderation/reputation.routes.js';
import moderationRoutes from '../modules/moderation/moderation.routes.js';
import zoomRoutes from '../modules/zoom/zoom.routes.js';
import knowledgeRoutes from '../modules/knowledge/knowledge.routes.js';
import askAiRoutes from '../modules/ai/ask-ai.routes.js';
import uploadRoutes from '../modules/upload/upload.routes.js';
import publicFaqRoutes from '../modules/faq/public-faq.routes.js';
import batchRoutes from '../modules/program/batch.routes.js';
import programRoutes from '../modules/program/program.routes.js';
import adminProgramSettingsRoutes from '../modules/program/admin-program-settings.routes.js';
import programZoomRoutes from '../modules/program/program-zoom.routes.js';
import programDiscordRoutes from '../modules/program/program-discord.routes.js';
import programFeatureFlagsRoutes from '../modules/program/program-feature-flags.routes.js';
import programAppSettingsRoutes from '../modules/program/program-app-settings.routes.js';
import courseRoutes from '../modules/program/course.routes.js';
import enrollmentRoutes from '../modules/program/enrollment.routes.js';
import supportRoutes from '../modules/support/support.routes.js';
import featureFlagRoutes from '../modules/program/feature-flag.routes.js';
import { documentRouter, documentAdminRouter } from '../modules/knowledge/documents.routes.js';
import welcomeRoutes from '../modules/program/welcome.routes.js';
import adminWelcomeRoutes from '../modules/admin/admin-welcome.routes.js';
import adminMentorRoutes from '../modules/admin/admin-mentor.routes.js';
import adminTimelineRoutes from '../modules/admin/admin-timeline.routes.js';
import { adminRouter as appSettingsAdminRouter, publicRouter as appSettingsPublicRouter } from '../modules/program/app-settings.routes.js';
import registrationControlRoutes from '../modules/program/registration-control.routes.js';
import adminCategoryClusterRoutes from '../modules/program/admin-category-cluster.routes.js';
import publicCategoryClusterRoutes from '../modules/program/public-category-cluster.routes.js';
import healthRoutes from '../modules/health/health.routes.js';

export function registerRoutes(app: Express): void {
  app.use('/api/auth', authRoutes);
  app.use('/api/faq', faqRoutes);
  app.use('/api/community', communityRoutes);
  app.use('/api/search', searchRoutes);
  app.use('/api/admin', adminRoutes);
  app.use('/api/admin', adminAutoAnswerRoutes);
  app.use('/api/admin', adminAuditRoutes);
  app.use('/api/reputation', reputationRoutes);
  app.use('/api/moderation', moderationRoutes);
  app.use('/api/analytics', analyticsRoutes);
  app.use('/api/notifications', notificationRoutes);
  app.use('/api/notifications/tea', teaRoutes);
  app.use('/api/zoom', zoomRoutes);
  app.use('/api/knowledge', knowledgeRoutes);
  app.use('/api/ask-ai', askAiRoutes);
  app.use('/api/upload', uploadRoutes);
  app.use('/api/public', publicFaqRoutes);
  app.use('/api/health', healthRoutes);
  app.use('/api/batches', batchRoutes);
  app.use('/api/programs', programRoutes);
  app.use('/api/admin/programs', adminProgramSettingsRoutes);
  app.use('/api/admin/programs', programZoomRoutes);
  app.use('/api/admin/programs', programDiscordRoutes);
  app.use('/api/admin/programs', programFeatureFlagsRoutes);
  app.use('/api/admin/programs', programAppSettingsRoutes);
  app.use('/api/admin/programs/:batchId/category-clusters', adminCategoryClusterRoutes);
  app.use('/api/public/category-clusters', publicCategoryClusterRoutes);
  app.use('/api/courses', courseRoutes);
  app.use('/api', enrollmentRoutes);
  app.use('/api/support', supportRoutes);
  app.use('/api/feature-flags', featureFlagRoutes);
  app.use('/api/documents',       documentRouter);
  app.use('/api/admin/documents', documentAdminRouter);
  app.use('/api/welcome', welcomeRoutes);
  app.use('/api/admin/welcome', adminWelcomeRoutes);
  app.use('/api/admin/mentors', adminMentorRoutes);
  app.use('/api/admin/timeline-steps', adminTimelineRoutes);
  app.use('/api/admin/settings',  appSettingsAdminRouter);
  app.use('/api/public/settings', appSettingsPublicRouter);
  app.use('/api/admin/registration-config', registrationControlRoutes);
}
